// do not edit, auto generated by curdboy

package curd

type QueryRequest struct{
	Filter string
  Fields string
	PageIndex int
	PageSize int
}

type UpdateRequest struct{
  Filter string
  Data map[string]any
}
