// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/pigfall/demo-kratos-curdboy/ent"
	"github.com/pigfall/demo-kratos-curdboy/internal/biz"
	"github.com/pigfall/demo-kratos-curdboy/internal/conf"
	"github.com/pigfall/demo-kratos-curdboy/internal/data"
	"github.com/pigfall/demo-kratos-curdboy/internal/server"
	"github.com/pigfall/demo-kratos-curdboy/internal/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, client *ent.Client) (*kratos.App, func(), error) {
	userStorage := data.NewUserStorage(client)
	userBiz := biz.NewUserBiz(userStorage)
	userSvc := service.NewUserSvc(userBiz)
	deptStorage := data.NewDeptStorage(client)
	deptBiz := biz.NewDeptBiz(deptStorage)
	deptSvc := service.NewDeptSvc(deptBiz)
	carStorage := data.NewCarStorage(client)
	carBiz := biz.NewCarBiz(carStorage)
	carSvc := service.NewCarSvc(carBiz)
	grpcServer := server.NewGRPCServer(confServer, userSvc, deptSvc, carSvc, logger)
	httpServer := server.NewHTTPServer(confServer, userSvc, deptSvc, carSvc, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
