version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'curdboy'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'devpassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'